### ISSUE TITLE
User can sort entries by date

### ISSUE THREAD

**Issue by Cole-Allen** [Cole-Allen/code-journal#9]
## :spiral_notepad: Plan :spiral_notepad:
Add a button to change the sorting of entries at the top of the page

## ✅ Task List ✅

- [x] Add a selection box at the top of the entries page that switches between most recent posts and oldest posts
- [x] Add date property to data object
- [x] Have date property be automatically assigned current date/time
- [x] Test in private browsing
- [x] Fix any errors
